title: Uncertain Futures Project
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Uncertain Futures is a collaborative artwork highlighting intersectional issues around work for women over 50 focusing on gender, age, race, disability and class. 
baseurl: "/Uncertain-Futures"  # the subpath of your site, e.g. /blog
url: "https://mnvnery.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
permalink: pretty 
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
