backend:
  name: git-gateway
  branch: master

media_folder: "assets/img"

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Home'
        name: "home"
        file: 'index.html'
        fields:
          - { label: 'Slideshow', name: 'slideshow', widget: list, field: {label: Image, name: image, widget: image}}
          - { label: 'About the Project', name: about_the_project, widget: markdown, modes: [rich_text] }
          - { widget: image, name: image_1, label: "Image 1" }
          - { label: 'Timeline', name: impact_tracker, widget: markdown, modes: [rich_text] }
          - { widget: image, name: image_2, label: "Image 2" }
          - widget: list
            name: years
            label: "Years" 
            fields: 
              - { label: Year, name: year, widget: string }
              - label: Months
                name: months
                widget: list
                fields: 
                  - { label: Month, name: month, widget: string }
                  - label: Events
                    name: events
                    widget: list
                    fields:
                      - { label: Event, name: event, widget: markdown, modes: [rich_text] }
                      - { label: Top or Bottom, name: top_or_bottom, widget: boolean }
                      - { label: Wider, name: wider, widget: boolean, hint: 'Turn on if there is a lot of text.' }
      - label: Team
        name: team
        file: team.html
        fields:
          - label: Research Team Fields
            name: research_team_fields
            widget: list
            fields:
              - { label: Title, name: title, widget: string, required: false  }
              - { label: Description, name: description, widget: markdown, modes: [rich_text], required: false  }
          - label: The Advisory Group
            name: the_advisory_group
            widget: list
            fields:
              - { label: Name, name: name, widget: string, required: false }
              - { label: Description, name: description, widget: markdown, modes: [rich_text], required: false }
              - { widget: image, name: portrait, label: "Portrait", required: false }
          - label: Team Profiles
            name: team_profiles
            widget: list
            fields:
              - { label: Name, name: name, widget: string, required: false }
              - { label: Title, name: title, widget: string, required: false }
              - { label: Institution, name: institution, widget: string, required: false }
              - { label: Information, name: information, widget: markdown, modes: [rich_text], required: false }
              - { widget: image, name: image, label: "Image", required: false }
              - { label: Link, name: link, widget: string, required: false}
              - label: "Section"
                name: "section"
                widget: "select"
                required: false
                options: ["Project Design and Management", "Participatory Research", "Artistic Productions", "Sponsors"]
      - label: Phase 1 
        name: phase-1
        file: phase1.html
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Information, name: info, widget: markdown, modes: [rich_text], hint: "use 'heading 3' for titles", required: false   }
      - label: Phase 2
        name: phase-2
        file: phase2.html
        fields:
          - { label: Title, name: title, widget: string  }
          - { label: Information, name: info, widget: markdown, modes: [rich_text], hint: "use 'heading 3' for titles", required: false  }
      - label: Research Themes
        name: research-themes
        file: research-themes.html
        fields:
          - label: Themes
            name: themes
            widget: list
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Subtitle, name: subtitle, widget: string, required: false  }
              - { label: Info, name: info, widget: markdown, modes: [rich_text], required: false  }
      - label: 'Aesthetic Productions'
        name: "aesthetic-productions"
        file: 'aesthetic-productions.html'
        fields:
          - label: 'Page Blocks'
            name: 'page_blocks'
            widget: list
            types: 
              - label: Text Block 
                name: text-block
                widget: object
                fields:
                  - { label: Text, name: text, widget: markdown, modes: [rich_text], required: false }
              - label: Single Image
                name: blank-image
                widget: object
                fields: 
                  - { label: Image , name: image , widget: image }
              - label: Multi Image
                name: multi-image
                widget: object
                fields:
                  - { label: 'Multi Images', name: 'multi-images', widget: list, field: {label: Image, name: image, widget: image}}
              - label: Video Upload
                name: video-upload
                widget: object
                fields:
                  - { label: Video Link, name: video_link, widget: string }
